// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6D5EbGEmBZwqo2AdwE_ppDl0Pok1Mmok',
    appId: '1:777596625161:web:74b322ee3a900bbaadf3d8',
    messagingSenderId: '777596625161',
    projectId: 'to-do-list-c3a55',
    authDomain: 'to-do-list-c3a55.firebaseapp.com',
    storageBucket: 'to-do-list-c3a55.appspot.com',
    measurementId: 'G-XS22X2V149',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC88D_DKTIxSCMtAiGymsyw4NxoSKenNSk',
    appId: '1:777596625161:android:de4fa6e9917a0cf3adf3d8',
    messagingSenderId: '777596625161',
    projectId: 'to-do-list-c3a55',
    storageBucket: 'to-do-list-c3a55.appspot.com',
  );
}
